version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-sam-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5rewn7scefv7"
s3_prefix = "test-sam-stack"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
